name: Run Journey Tests on GitHub
description: Run journey tests using the DEFRA CDP node journey test suite template

inputs:
  example-node-backend:
    required: false
    type: string
  example-node-frontend:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: DEFRA/cdp-node-journey-test-suite-template

    - name: Docker Login
      uses: DEFRA/cdp-build-action/docker-login@main

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - name: Setup the tests
      run: npm ci
      shell: bash
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium chromium-headless-shell
      shell: bash
    - name: Start docker compose
      shell: bash
      run: |
          CDP_EXAMPLE_NODE_FRONTEND=${{inputs.example-node-frontend}} \
          CDP_EXAMPLE_NODE_BACKEND=${{inputs.example-node-backend}} \
          docker compose up --wait-timeout 300 -d --quiet-pull
    - name: Start OWASP ZAP
      shell: bash
      run: |
        docker pull ghcr.io/zaproxy/zaproxy:stable

        docker run -d --name zap \
          --dns 8.8.8.8 \
          -p 8080:8080 \
          ghcr.io/zaproxy/zaproxy:stable \
          zap.sh -daemon -host 0.0.0.0 -port 8080 \
          -config api.disablekey=true \
          -config api.addrs.addr.name=.* \
          -config api.addrs.addr.regex=true

        echo "Waiting for ZAP..."

        for i in {1..30}; do
          if curl -s http://127.0.0.1:8080/JSON/core/view/version/; then
            echo "ZAP ready"
            exit 0
          fi

          if ! docker ps --filter "name=zap-test" --filter "status=running" | grep -q zap-test; then
            echo "ZAP container stopped"
            docker logs zap-test
            exit 1
          fi

          sleep 2
        done

        echo "ZAP failed to start"
        docker logs zap-test
        exit 1


    - name: Run the tests
      shell: bash
      run: |
        npm run test

    - name: Run security tests
      shell: bash
      run: npm run test:security

    - name: Stop OWASP ZAP
      if: always()
      shell: bash
      run: docker rm -f zap || true

    - name: Upload ZAP security report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zap-security-report
        path: ./zap-report/zap-report.html

    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash
    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report
    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt
