name: Run Journey Tests on GitHub

permissions:
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    name: Run Journey Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-journey-tests
